### ISSUE TITLE
Project initialization,Dependency problem,glob@7.2.3: Glob versions prior to v9 are no longer supported

### ISSUE THREAD

**Issue by Paulssz** [caoxiemeihao/electron-vue-vite#514]
 npm i
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn cleanup Failed to remove some directories [
npm warn cleanup   [
npm warn cleanup     'D:\\project\\electron-vite-project\\node_modules',
npm warn cleanup     [Error: EPERM: operation not permitted, rmdir 'D:\project\electron-vite-project\node_modules\@isaacs\cliui'] {
npm warn cleanup       errno: -4048,
npm warn cleanup       code: 'EPERM',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'D:\\project\\electron-vite-project\\node_modules\\@isaacs\\cliui'
npm warn cleanup     }
npm warn cleanup   ]
npm warn cleanup ]
npm error code 1
npm error path D:\project\electron-vite-project\node_modules\electron
npm error command failed
npm error command C:\Windows\system32\cmd.exe /d /s /c node install.js
npm error RequestError: connect ETIMEDOUT 20.205.243.166:443
npm error     at ClientRequest.<anonymous> (D:\project\electron-vite-project\node_modules\got\dist\source\core\index.js:970:111)
npm error     at Object.onceWrapper (node:events:633:26)
npm error     at ClientRequest.emit (node:events:530:35)
npm error     at origin.emit (D:\project\electron-vite-project\node_modules\@szmarczak\http-timer\dist\source\index.js:43:20)
npm error     at TLSSocket.socketErrorListener (node:_http_client:495:9)
npm error     at TLSSocket.emit (node:events:518:28)
npm error     at emitErrorNT (node:internal/streams/destroy:169:8)
npm error     at emitErrorCloseNT (node:internal/streams/destroy:128:3)
npm error     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
npm error     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
npm error A complete log of this run can be found in: C:\Program Files\nodejs\node_cache\_logs\2024-09-14T09_47_36_283Z-debug-0.log

**Comment by JXDS18FUJT** [comment]
check you node version maybe cant fix electron

**Comment by subframe7536** [comment]
Close for stale
